# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\animator.well\github-repertories\maya-toolkit-weight-manager\tk_weight_manager\ui\resource\designer\manager_qt.ui'
#
# Created: Sun Apr 23 02:48:29 2017
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from QtSide import QtCore, QtGui, QtWidgets

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtWidgets.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtWidgets.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtWidgets.QApplication.translate(context, text, disambig)

class Ui_skinClusterManager_Dialog(object):
    def setupUi(self, skinClusterManager_Dialog):
        skinClusterManager_Dialog.setObjectName(_fromUtf8("skinClusterManager_Dialog"))
        skinClusterManager_Dialog.resize(295, 392)
        self.skinClusterManager_Dialog_verticalLayout = QtWidgets.QVBoxLayout(skinClusterManager_Dialog)
        self.skinClusterManager_Dialog_verticalLayout.setSpacing(4)
        self.skinClusterManager_Dialog_verticalLayout.setObjectName(_fromUtf8("skinClusterManager_Dialog_verticalLayout"))
        self.skinClusterManager_menu_horizontalLayout = QtWidgets.QHBoxLayout()
        self.skinClusterManager_menu_horizontalLayout.setSpacing(2)
        self.skinClusterManager_menu_horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.skinClusterManager_menu_horizontalLayout.setObjectName(_fromUtf8("skinClusterManager_menu_horizontalLayout"))
        self.skinClusterManager_home_pushButton = QtWidgets.QPushButton(skinClusterManager_Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.skinClusterManager_home_pushButton.sizePolicy().hasHeightForWidth())
        self.skinClusterManager_home_pushButton.setSizePolicy(sizePolicy)
        self.skinClusterManager_home_pushButton.setMaximumSize(QtCore.QSize(25, 25))
        self.skinClusterManager_home_pushButton.setFlat(True)
        self.skinClusterManager_home_pushButton.setObjectName(_fromUtf8("skinClusterManager_home_pushButton"))
        self.skinClusterManager_menu_horizontalLayout.addWidget(self.skinClusterManager_home_pushButton)
        self.skinClusterManager_folder_pushButton = QtWidgets.QPushButton(skinClusterManager_Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.skinClusterManager_folder_pushButton.sizePolicy().hasHeightForWidth())
        self.skinClusterManager_folder_pushButton.setSizePolicy(sizePolicy)
        self.skinClusterManager_folder_pushButton.setMaximumSize(QtCore.QSize(25, 25))
        self.skinClusterManager_folder_pushButton.setFlat(True)
        self.skinClusterManager_folder_pushButton.setObjectName(_fromUtf8("skinClusterManager_folder_pushButton"))
        self.skinClusterManager_menu_horizontalLayout.addWidget(self.skinClusterManager_folder_pushButton)
        self.skinClusterManager_refresh_pushButton = QtWidgets.QPushButton(skinClusterManager_Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.skinClusterManager_refresh_pushButton.sizePolicy().hasHeightForWidth())
        self.skinClusterManager_refresh_pushButton.setSizePolicy(sizePolicy)
        self.skinClusterManager_refresh_pushButton.setMaximumSize(QtCore.QSize(25, 25))
        self.skinClusterManager_refresh_pushButton.setFlat(True)
        self.skinClusterManager_refresh_pushButton.setObjectName(_fromUtf8("skinClusterManager_refresh_pushButton"))
        self.skinClusterManager_menu_horizontalLayout.addWidget(self.skinClusterManager_refresh_pushButton)
        self.skinClusterManager_vis_pushButton = QtWidgets.QPushButton(skinClusterManager_Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.skinClusterManager_vis_pushButton.sizePolicy().hasHeightForWidth())
        self.skinClusterManager_vis_pushButton.setSizePolicy(sizePolicy)
        self.skinClusterManager_vis_pushButton.setMaximumSize(QtCore.QSize(25, 25))
        self.skinClusterManager_vis_pushButton.setFlat(True)
        self.skinClusterManager_vis_pushButton.setObjectName(_fromUtf8("skinClusterManager_vis_pushButton"))
        self.skinClusterManager_menu_horizontalLayout.addWidget(self.skinClusterManager_vis_pushButton)
        self.skinClusterManager_tool_pushButton = QtWidgets.QPushButton(skinClusterManager_Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.skinClusterManager_tool_pushButton.sizePolicy().hasHeightForWidth())
        self.skinClusterManager_tool_pushButton.setSizePolicy(sizePolicy)
        self.skinClusterManager_tool_pushButton.setMaximumSize(QtCore.QSize(25, 25))
        self.skinClusterManager_tool_pushButton.setFlat(True)
        self.skinClusterManager_tool_pushButton.setObjectName(_fromUtf8("skinClusterManager_tool_pushButton"))
        self.skinClusterManager_menu_horizontalLayout.addWidget(self.skinClusterManager_tool_pushButton)
        self.skinClusterManager_path_LineEdit = QtWidgets.QLineEdit(skinClusterManager_Dialog)
        self.skinClusterManager_path_LineEdit.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.skinClusterManager_path_LineEdit.sizePolicy().hasHeightForWidth())
        self.skinClusterManager_path_LineEdit.setSizePolicy(sizePolicy)
        self.skinClusterManager_path_LineEdit.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.skinClusterManager_path_LineEdit.setReadOnly(True)
        self.skinClusterManager_path_LineEdit.setObjectName(_fromUtf8("skinClusterManager_path_LineEdit"))
        self.skinClusterManager_menu_horizontalLayout.addWidget(self.skinClusterManager_path_LineEdit)
        self.skinClusterManager_path_pushButton = QtWidgets.QPushButton(skinClusterManager_Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.skinClusterManager_path_pushButton.sizePolicy().hasHeightForWidth())
        self.skinClusterManager_path_pushButton.setSizePolicy(sizePolicy)
        self.skinClusterManager_path_pushButton.setMaximumSize(QtCore.QSize(16, 25))
        self.skinClusterManager_path_pushButton.setIconSize(QtCore.QSize(12, 12))
        self.skinClusterManager_path_pushButton.setFlat(True)
        self.skinClusterManager_path_pushButton.setObjectName(_fromUtf8("skinClusterManager_path_pushButton"))
        self.skinClusterManager_menu_horizontalLayout.addWidget(self.skinClusterManager_path_pushButton)
        self.skinClusterManager_Dialog_verticalLayout.addLayout(self.skinClusterManager_menu_horizontalLayout)
        self.skinClusterManager_horizontalLayout = QtWidgets.QHBoxLayout()
        self.skinClusterManager_horizontalLayout.setSpacing(3)
        self.skinClusterManager_horizontalLayout.setObjectName(_fromUtf8("skinClusterManager_horizontalLayout"))
        self.skinClusterManager_one_listWidget = QtWidgets.QListWidget(skinClusterManager_Dialog)
        self.skinClusterManager_one_listWidget.setFocusPolicy(QtCore.Qt.NoFocus)
        self.skinClusterManager_one_listWidget.setObjectName(_fromUtf8("skinClusterManager_one_listWidget"))
        self.skinClusterManager_horizontalLayout.addWidget(self.skinClusterManager_one_listWidget)
        self.skinClusterManager_two_listWidget = QtWidgets.QListWidget(skinClusterManager_Dialog)
        self.skinClusterManager_two_listWidget.setFocusPolicy(QtCore.Qt.NoFocus)
        self.skinClusterManager_two_listWidget.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.skinClusterManager_two_listWidget.setObjectName(_fromUtf8("skinClusterManager_two_listWidget"))
        self.skinClusterManager_horizontalLayout.addWidget(self.skinClusterManager_two_listWidget)
        self.skinClusterManager_tools_groupBox_verticalLayout = QtWidgets.QVBoxLayout()
        self.skinClusterManager_tools_groupBox_verticalLayout.setSpacing(3)
        self.skinClusterManager_tools_groupBox_verticalLayout.setObjectName(_fromUtf8("skinClusterManager_tools_groupBox_verticalLayout"))
        self.skinClusterManager_one_groupBox = QtWidgets.QGroupBox(skinClusterManager_Dialog)
        self.skinClusterManager_one_groupBox.setTitle(_fromUtf8(""))
        self.skinClusterManager_one_groupBox.setObjectName(_fromUtf8("skinClusterManager_one_groupBox"))
        self.skinClusterManager_one_groupBox_verticalLayout = QtWidgets.QVBoxLayout(self.skinClusterManager_one_groupBox)
        self.skinClusterManager_one_groupBox_verticalLayout.setSpacing(2)
        self.skinClusterManager_one_groupBox_verticalLayout.setObjectName(_fromUtf8("skinClusterManager_one_groupBox_verticalLayout"))
        self.skinClusterManager_export_pushButton = QtWidgets.QPushButton(self.skinClusterManager_one_groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.skinClusterManager_export_pushButton.sizePolicy().hasHeightForWidth())
        self.skinClusterManager_export_pushButton.setSizePolicy(sizePolicy)
        self.skinClusterManager_export_pushButton.setMaximumSize(QtCore.QSize(25, 25))
        self.skinClusterManager_export_pushButton.setFlat(True)
        self.skinClusterManager_export_pushButton.setObjectName(_fromUtf8("skinClusterManager_export_pushButton"))
        self.skinClusterManager_one_groupBox_verticalLayout.addWidget(self.skinClusterManager_export_pushButton)
        self.skinClusterManager_exportComponents_pushButton = QtWidgets.QPushButton(self.skinClusterManager_one_groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.skinClusterManager_exportComponents_pushButton.sizePolicy().hasHeightForWidth())
        self.skinClusterManager_exportComponents_pushButton.setSizePolicy(sizePolicy)
        self.skinClusterManager_exportComponents_pushButton.setMaximumSize(QtCore.QSize(25, 25))
        self.skinClusterManager_exportComponents_pushButton.setFlat(True)
        self.skinClusterManager_exportComponents_pushButton.setObjectName(_fromUtf8("skinClusterManager_exportComponents_pushButton"))
        self.skinClusterManager_one_groupBox_verticalLayout.addWidget(self.skinClusterManager_exportComponents_pushButton)
        self.skinClusterManager_one_groupBox_one_line = QtWidgets.QFrame(self.skinClusterManager_one_groupBox)
        self.skinClusterManager_one_groupBox_one_line.setFrameShape(QtWidgets.QFrame.HLine)
        self.skinClusterManager_one_groupBox_one_line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.skinClusterManager_one_groupBox_one_line.setObjectName(_fromUtf8("skinClusterManager_one_groupBox_one_line"))
        self.skinClusterManager_one_groupBox_verticalLayout.addWidget(self.skinClusterManager_one_groupBox_one_line)
        self.skinClusterManager_import_pushButton = QtWidgets.QPushButton(self.skinClusterManager_one_groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.skinClusterManager_import_pushButton.sizePolicy().hasHeightForWidth())
        self.skinClusterManager_import_pushButton.setSizePolicy(sizePolicy)
        self.skinClusterManager_import_pushButton.setMaximumSize(QtCore.QSize(25, 25))
        self.skinClusterManager_import_pushButton.setFlat(True)
        self.skinClusterManager_import_pushButton.setObjectName(_fromUtf8("skinClusterManager_import_pushButton"))
        self.skinClusterManager_one_groupBox_verticalLayout.addWidget(self.skinClusterManager_import_pushButton)
        self.skinClusterManager_batchImport_pushButton = QtWidgets.QPushButton(self.skinClusterManager_one_groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.skinClusterManager_batchImport_pushButton.sizePolicy().hasHeightForWidth())
        self.skinClusterManager_batchImport_pushButton.setSizePolicy(sizePolicy)
        self.skinClusterManager_batchImport_pushButton.setMaximumSize(QtCore.QSize(25, 25))
        self.skinClusterManager_batchImport_pushButton.setFlat(True)
        self.skinClusterManager_batchImport_pushButton.setObjectName(_fromUtf8("skinClusterManager_batchImport_pushButton"))
        self.skinClusterManager_one_groupBox_verticalLayout.addWidget(self.skinClusterManager_batchImport_pushButton)
        self.skinClusterManager_one_groupBox_two_line = QtWidgets.QFrame(self.skinClusterManager_one_groupBox)
        self.skinClusterManager_one_groupBox_two_line.setFrameShape(QtWidgets.QFrame.HLine)
        self.skinClusterManager_one_groupBox_two_line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.skinClusterManager_one_groupBox_two_line.setObjectName(_fromUtf8("skinClusterManager_one_groupBox_two_line"))
        self.skinClusterManager_one_groupBox_verticalLayout.addWidget(self.skinClusterManager_one_groupBox_two_line)
        self.skinClusterManager_getInfluenceFromWeightData_pushButton = QtWidgets.QPushButton(self.skinClusterManager_one_groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.skinClusterManager_getInfluenceFromWeightData_pushButton.sizePolicy().hasHeightForWidth())
        self.skinClusterManager_getInfluenceFromWeightData_pushButton.setSizePolicy(sizePolicy)
        self.skinClusterManager_getInfluenceFromWeightData_pushButton.setMaximumSize(QtCore.QSize(25, 25))
        self.skinClusterManager_getInfluenceFromWeightData_pushButton.setFlat(True)
        self.skinClusterManager_getInfluenceFromWeightData_pushButton.setObjectName(_fromUtf8("skinClusterManager_getInfluenceFromWeightData_pushButton"))
        self.skinClusterManager_one_groupBox_verticalLayout.addWidget(self.skinClusterManager_getInfluenceFromWeightData_pushButton)
        self.skinClusterManager_trash_pushButton = QtWidgets.QPushButton(self.skinClusterManager_one_groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.skinClusterManager_trash_pushButton.sizePolicy().hasHeightForWidth())
        self.skinClusterManager_trash_pushButton.setSizePolicy(sizePolicy)
        self.skinClusterManager_trash_pushButton.setMaximumSize(QtCore.QSize(25, 25))
        self.skinClusterManager_trash_pushButton.setFlat(True)
        self.skinClusterManager_trash_pushButton.setObjectName(_fromUtf8("skinClusterManager_trash_pushButton"))
        self.skinClusterManager_one_groupBox_verticalLayout.addWidget(self.skinClusterManager_trash_pushButton)
        self.skinClusterManager_reload_pushButton = QtWidgets.QPushButton(self.skinClusterManager_one_groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.skinClusterManager_reload_pushButton.sizePolicy().hasHeightForWidth())
        self.skinClusterManager_reload_pushButton.setSizePolicy(sizePolicy)
        self.skinClusterManager_reload_pushButton.setMaximumSize(QtCore.QSize(25, 25))
        self.skinClusterManager_reload_pushButton.setFlat(True)
        self.skinClusterManager_reload_pushButton.setObjectName(_fromUtf8("skinClusterManager_reload_pushButton"))
        self.skinClusterManager_one_groupBox_verticalLayout.addWidget(self.skinClusterManager_reload_pushButton)
        self.skinClusterManager_tools_groupBox_verticalLayout.addWidget(self.skinClusterManager_one_groupBox)
        self.skinClusterManager_two_groupBox = QtWidgets.QGroupBox(skinClusterManager_Dialog)
        self.skinClusterManager_two_groupBox.setTitle(_fromUtf8(""))
        self.skinClusterManager_two_groupBox.setObjectName(_fromUtf8("skinClusterManager_two_groupBox"))
        self.skinClusterManager_two_groupBox_verticalLayout = QtWidgets.QVBoxLayout(self.skinClusterManager_two_groupBox)
        self.skinClusterManager_two_groupBox_verticalLayout.setSpacing(2)
        self.skinClusterManager_two_groupBox_verticalLayout.setObjectName(_fromUtf8("skinClusterManager_two_groupBox_verticalLayout"))
        self.skinClusterManager_getInfluence_pushButton = QtWidgets.QPushButton(self.skinClusterManager_two_groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.skinClusterManager_getInfluence_pushButton.sizePolicy().hasHeightForWidth())
        self.skinClusterManager_getInfluence_pushButton.setSizePolicy(sizePolicy)
        self.skinClusterManager_getInfluence_pushButton.setMaximumSize(QtCore.QSize(25, 25))
        self.skinClusterManager_getInfluence_pushButton.setFlat(True)
        self.skinClusterManager_getInfluence_pushButton.setObjectName(_fromUtf8("skinClusterManager_getInfluence_pushButton"))
        self.skinClusterManager_two_groupBox_verticalLayout.addWidget(self.skinClusterManager_getInfluence_pushButton)
        self.skinClusterManager_holdInfluence_pushButton = QtWidgets.QPushButton(self.skinClusterManager_two_groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.skinClusterManager_holdInfluence_pushButton.sizePolicy().hasHeightForWidth())
        self.skinClusterManager_holdInfluence_pushButton.setSizePolicy(sizePolicy)
        self.skinClusterManager_holdInfluence_pushButton.setMaximumSize(QtCore.QSize(25, 25))
        self.skinClusterManager_holdInfluence_pushButton.setFlat(True)
        self.skinClusterManager_holdInfluence_pushButton.setObjectName(_fromUtf8("skinClusterManager_holdInfluence_pushButton"))
        self.skinClusterManager_two_groupBox_verticalLayout.addWidget(self.skinClusterManager_holdInfluence_pushButton)
        self.skinClusterManager_unHoldSelectedInfluence_pushButton = QtWidgets.QPushButton(self.skinClusterManager_two_groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.skinClusterManager_unHoldSelectedInfluence_pushButton.sizePolicy().hasHeightForWidth())
        self.skinClusterManager_unHoldSelectedInfluence_pushButton.setSizePolicy(sizePolicy)
        self.skinClusterManager_unHoldSelectedInfluence_pushButton.setMaximumSize(QtCore.QSize(25, 25))
        self.skinClusterManager_unHoldSelectedInfluence_pushButton.setFlat(True)
        self.skinClusterManager_unHoldSelectedInfluence_pushButton.setObjectName(_fromUtf8("skinClusterManager_unHoldSelectedInfluence_pushButton"))
        self.skinClusterManager_two_groupBox_verticalLayout.addWidget(self.skinClusterManager_unHoldSelectedInfluence_pushButton)
        self.skinClusterManager_two_groupBox_line = QtWidgets.QFrame(self.skinClusterManager_two_groupBox)
        self.skinClusterManager_two_groupBox_line.setFrameShape(QtWidgets.QFrame.HLine)
        self.skinClusterManager_two_groupBox_line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.skinClusterManager_two_groupBox_line.setObjectName(_fromUtf8("skinClusterManager_two_groupBox_line"))
        self.skinClusterManager_two_groupBox_verticalLayout.addWidget(self.skinClusterManager_two_groupBox_line)
        self.skinClusterManager_resetBindPose_pushButton = QtWidgets.QPushButton(self.skinClusterManager_two_groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.skinClusterManager_resetBindPose_pushButton.sizePolicy().hasHeightForWidth())
        self.skinClusterManager_resetBindPose_pushButton.setSizePolicy(sizePolicy)
        self.skinClusterManager_resetBindPose_pushButton.setMaximumSize(QtCore.QSize(25, 25))
        self.skinClusterManager_resetBindPose_pushButton.setFlat(True)
        self.skinClusterManager_resetBindPose_pushButton.setObjectName(_fromUtf8("skinClusterManager_resetBindPose_pushButton"))
        self.skinClusterManager_two_groupBox_verticalLayout.addWidget(self.skinClusterManager_resetBindPose_pushButton)
        self.skinClusterManager_removeUnusedInfluence_pushButton = QtWidgets.QPushButton(self.skinClusterManager_two_groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.skinClusterManager_removeUnusedInfluence_pushButton.sizePolicy().hasHeightForWidth())
        self.skinClusterManager_removeUnusedInfluence_pushButton.setSizePolicy(sizePolicy)
        self.skinClusterManager_removeUnusedInfluence_pushButton.setMaximumSize(QtCore.QSize(25, 25))
        self.skinClusterManager_removeUnusedInfluence_pushButton.setFlat(True)
        self.skinClusterManager_removeUnusedInfluence_pushButton.setObjectName(_fromUtf8("skinClusterManager_removeUnusedInfluence_pushButton"))
        self.skinClusterManager_two_groupBox_verticalLayout.addWidget(self.skinClusterManager_removeUnusedInfluence_pushButton)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.skinClusterManager_two_groupBox_verticalLayout.addItem(spacerItem)
        self.skinClusterManager_tools_groupBox_verticalLayout.addWidget(self.skinClusterManager_two_groupBox)
        self.skinClusterManager_horizontalLayout.addLayout(self.skinClusterManager_tools_groupBox_verticalLayout)
        self.skinClusterManager_horizontalLayout.setStretch(0, 3)
        self.skinClusterManager_horizontalLayout.setStretch(1, 5)
        self.skinClusterManager_Dialog_verticalLayout.addLayout(self.skinClusterManager_horizontalLayout)
        self.skinClusterManager_progressBar = QtWidgets.QProgressBar(skinClusterManager_Dialog)
        self.skinClusterManager_progressBar.setEnabled(True)
        self.skinClusterManager_progressBar.setMaximumSize(QtCore.QSize(16777215, 8))
        self.skinClusterManager_progressBar.setTextVisible(False)
        self.skinClusterManager_progressBar.setObjectName(_fromUtf8("skinClusterManager_progressBar"))
        self.skinClusterManager_Dialog_verticalLayout.addWidget(self.skinClusterManager_progressBar)

        self.retranslateUi(skinClusterManager_Dialog)
        QtCore.QMetaObject.connectSlotsByName(skinClusterManager_Dialog)

    def retranslateUi(self, skinClusterManager_Dialog):
        skinClusterManager_Dialog.setWindowTitle(_translate("skinClusterManager_Dialog", "SkinCluster - Manager", None))
        self.skinClusterManager_home_pushButton.setToolTip(_translate("skinClusterManager_Dialog", "set root path", None))
        self.skinClusterManager_folder_pushButton.setToolTip(_translate("skinClusterManager_Dialog", "new folder", None))
        self.skinClusterManager_refresh_pushButton.setToolTip(_translate("skinClusterManager_Dialog", "refresh", None))
        self.skinClusterManager_vis_pushButton.setToolTip(_translate("skinClusterManager_Dialog", "visibility control", None))
        self.skinClusterManager_tool_pushButton.setToolTip(_translate("skinClusterManager_Dialog", "toolkits", None))
        self.skinClusterManager_export_pushButton.setToolTip(_translate("skinClusterManager_Dialog", "export weights", None))
        self.skinClusterManager_exportComponents_pushButton.setToolTip(_translate("skinClusterManager_Dialog", "export components weights", None))
        self.skinClusterManager_import_pushButton.setToolTip(_translate("skinClusterManager_Dialog", "import weights", None))
        self.skinClusterManager_batchImport_pushButton.setToolTip(_translate("skinClusterManager_Dialog", "batch import weights", None))
        self.skinClusterManager_getInfluenceFromWeightData_pushButton.setToolTip(_translate("skinClusterManager_Dialog", "get influences from data", None))
        self.skinClusterManager_trash_pushButton.setToolTip(_translate("skinClusterManager_Dialog", "delete", None))
        self.skinClusterManager_reload_pushButton.setToolTip(_translate("skinClusterManager_Dialog", "refresh", None))
        self.skinClusterManager_getInfluence_pushButton.setToolTip(_translate("skinClusterManager_Dialog", "get influences", None))
        self.skinClusterManager_holdInfluence_pushButton.setToolTip(_translate("skinClusterManager_Dialog", "hold influences", None))
        self.skinClusterManager_unHoldSelectedInfluence_pushButton.setToolTip(_translate("skinClusterManager_Dialog", "unhold selected influences", None))
        self.skinClusterManager_resetBindPose_pushButton.setToolTip(_translate("skinClusterManager_Dialog", "reset bind pose ", None))
        self.skinClusterManager_removeUnusedInfluence_pushButton.setToolTip(_translate("skinClusterManager_Dialog", "remove unused influences", None))

